apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: l4
spec:
  activeMigration:
    optimizeRulePriority: true
  nodePoolAutoCreation:
    enabled: true
  priorities:
      # Use spot
    - gpu:
        type: nvidia-l4
        count: 2
        driverVersion: latest
      machineType: g2-standard-24
      spot: true
      storage:
        secondaryBootDisks:
          - diskImageName: vllm-disk-image-sec
            mode: CONTAINER_IMAGE_CACHE 
    - flexStart:
        enabled: true
        nodeRecycling:
          leadTimeSeconds: 3600
      gpu:
        type: nvidia-l4
        count: 2
        driverVersion: latest
      machineType: g2-standard-24
      storage:
        secondaryBootDisks:
          - diskImageName: vllm-disk-image-sec
            mode: CONTAINER_IMAGE_CACHE 
    - gpu:
        type: nvidia-l4
        count: 2
        driverVersion: latest
      machineType: g2-standard-24
      storage:
        secondaryBootDisks:
          - diskImageName: vllm-disk-image-sec
            mode: CONTAINER_IMAGE_CACHE 
  whenUnsatisfiable: ScaleUpAnyway
